repos:
  # python import sorting - will amend files
  - repo: https://github.com/timothycrosley/isort
    rev: 4.3.21
    hooks:
    - id: isort
      language_version: python3.8

  # python code formatting - will amend files
  - repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
    - id: black
      language_version: python3.8

  # Flake8 includes pyflakes, pycodestyle, mccabe, pydocstyle, bandit
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.1
    hooks:
    - id: flake8
      language_version: python3.8

  # PEP8 linting, with added Django goodness
  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: v2.4.4
    hooks:
      - id: pylint
        language_version: python3.8