version: "3"
services:

    postgres:
      image: postgres:11.6
      ports:
        - "5432:5432"
      env_file:
        - ./.env.prod.db

    memcached:
      image: memcached:1.5
      ports:
        - "11211:11211"

    django:
      build:
        context: .
        dockerfile: Dockerfile.prod
      command: gunicorn atss.wsgi:application --bind 0.0.0.0:80 --workers 2
      container_name: atss-app-prod
      ports:
        - "80:80"
      volumes:
        - ./:/app
      depends_on:
        - memcached
        - postgres
      env_file:
        - ./.env.prod