FROM python:3.8.3-slim-buster

LABEL maintainer="Vladimir Melnichenko <melnichevv@gmail.com>"

# https://docs.docker.com/develop/develop-images/dockerfile_best-practices/
RUN apt-get update && apt-get install -y \
    build-essential gcc python3-dev \
    && apt-get clean

COPY requirements/ /app/requirements/
COPY scripts/ /app/scripts/
COPY data_inputs/ /app/data_inputs/

WORKDIR /app

ENV PYTHONPATH /app

RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir --requirement /app/requirements/prod.txt

#ONBUILD RUN /app/scripts/reset_docker_data.sh