# Generated by Django 3.0.6 on 2020-05-30 17:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FirewallRule",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("fw_id", models.CharField(db_index=True, max_length=20, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("source_tag", models.CharField(max_length=100)),
                ("dest_tag", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="VirtualMachine",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("vm_id", models.CharField(db_index=True, max_length=20, unique=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50), default=list, help_text="List of tags", size=None
                    ),
                ),
            ],
        ),
    ]
