# Generated by Django 3.0.6 on 2020-05-30 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="VirtualMachine",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("vm_id", models.CharField(db_index=True, max_length=20, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("tags", models.ManyToManyField(related_name="virtual_machines", to="vm.Tag")),
            ],
        ),
        migrations.CreateModel(
            name="FirewallRule",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("fw_id", models.CharField(db_index=True, max_length=20, unique=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "dest_tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="target_rules", to="vm.Tag"
                    ),
                ),
                (
                    "source_tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="source_rules", to="vm.Tag"
                    ),
                ),
            ],
        ),
    ]
